# Generated by Django 5.1.6 on 2025-04-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg', '0002_alter_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selectivesubject',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_selective',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clg.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_selective',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
