# Generated by Django 5.1.6 on 2025-04-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Понеділок'), ('Tuesday', 'Вівторок'), ('Wednesday', 'Середа'), ('Thursday', 'Четвер'), ('Friday', "П'ятниця"), ('Saturday', 'Субота')], default='Monday', max_length=10),
        ),
    ]
