# Generated by Django 5.1.6 on 2025-04-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg', '0005_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
