# Generated by Django 5.1.6 on 2025-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg', '0006_schedule_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='aim',
            field=models.CharField(choices=[('Lecture', 'Лек.'), ('Practice', 'Лаб.')], default='Lecture', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='week',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='selectivesubject',
            name='info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Понеділок'), ('Tuesday', 'Вівторок'), ('Wednesday', 'Середа'), ('Thursday', 'Четвер'), ('Friday', 'Пʼятниця'), ('Saturday', 'Субота')], default='Monday', max_length=10),
        ),
    ]
