# Generated by Django 5.2 on 2025-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg', '0007_schedule_aim_schedule_week_selectivesubject_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectivesubject',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
